# .github/workflows/release.yml

name: build, npm version && npm publish

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'npm version {major,minor,patch}'
        required: true

env:
  node_version: 22

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC and provenance
      contents: read   # Required to check out code
    steps:
    - uses: actions/checkout@v6
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js $
      uses: actions/setup-node@v6
      with:
        node-version: $
        # setting a registry enables the NODE_AUTH_TOKEN env variable
        # where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'
    - run: npm i
    - run: npm test
    - run: git config --global user.email "user@email.com"
    - run: git config --global user.name " $"
    - run: npm version $
    - run: npm publish --provenance
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
